import Footer from "@/components/footer";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: 'AboutUsCompany',
    description: "Generated by create next app",
    authors: {
        name: 'aaa',
        url: 'zzz'
    }
};
export default function AboutUsCompanyLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    console.log('AboutUsCompanyLayout')
    return (
        <div>
            AboutUsCompanyLayout
            <div>{children}</div>
            <Footer />
        </div>
    );
}
